

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: backend

    steps:
    - uses: actions/checkout@v4
    - name: Sparse Checkout
      run: |
        mkdir -p backend
        git sparse-checkout init --cone
        git sparse-checkout set backend
    - name: Copy content
      run: mv backend/* ./
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Stop backend
      run: sudo systemctl stop back
    - name: Build with Maven
      run: mvn -B clean package
    - name: Stop backend
      run: sudo systemctl start back

